### ISSUE TITLE
Error after saving the page

### ISSUE THREAD

**Issue by html-koder-com** [BookStackApp/BookStack#134]
Hi there!

Time to time (but very often) I got the error "Whoops, looks like something went wrong." after saving the edited page. Unfortunately I don't see any rule here... there are no exact steps to cause this error. From my point of view it happens randomly. 

Here is my laravel.log:

`[2016-06-23 09:15:53] production.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php:3178
Stack trace:
#0 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#3 /nodes/netwings/wiki/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(13274): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#8 /nodes/netwings/wiki/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(11822): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#13 /nodes/netwings/wiki/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(13009): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#18 /nodes/netwings/wiki/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(12946): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#23 /nodes/netwings/wiki/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(3237): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#28 /nodes/netwings/wiki/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#30 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(9828): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(2347): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /nodes/netwings/wiki/BookStack/bootstrap/cache/compiled.php(2331): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#33 /nodes/netwings/wiki/BookStack/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#34 {main}

`

**Comment by ssddanbrown** [comment]
Hi @html-koder-com, Sorry to hear you're having issues. Can you confirm your software stack for me?

- Operating System & version
- PHP version
- Web server software and version
- Database software and version

**Comment by html-koder-com** [comment]
Hi @ssddanbrown , here it is:

- **Operating System & version:**  Debian 8 Jessie
- **PHP version:**  5.6.22
- **Web server software and version:**  Apache 2.4
- **Database software and version:** Postgres 9.4

**Comment by CodeBrauer** [comment]
I had this too, but it only appears on creating a page without a chapter. If there was a chapter it saved.

**Comment by ssddanbrown** [comment]
@CodeBrauer That error sounds like #120. Check you're using php-mysqlnd rather than php-mysql. Alternatively it should be fixed on the master branch (Therefore in the next release).

@html-koder-com Thanks for the details. For BookStack Postgres is not officially supported at the moment (I'm not sure the custom search queries will work on postgres)but I wouldn't have thought that would be the cause of this issue. I'll replicate you environment at some point and see if I can find the cause.

**Comment by html-koder-com** [comment]
@ssddanbrown Please let me verify the database engine once more. We have more database instances on our server and I am not sure right now, if my previous answer (postgres) is coorect...

**Comment by html-koder-com** [comment]
@ssddanbrown Here is the update:

- **Database software and version:** MySQL: 5.1.49

**Comment by ssddanbrown** [comment]
@html-koder-com Thanks for checking but I'm kind of hoping that's incorrect again. MySQL 5.1.49 was released in July 2010. The minimum MySQL version for BookStack is 5.6 (Which is about equivalent to MariaDB 10).

Could you also check that all folders within the `storage` folder at writable by the server. Sessions are stored in here by default so it could be permissions effecting things.

**Comment by html-koder-com** [comment]
@ssddanbrown Hi there. Sorry for the delay (vacation).

Yes, the "storage" folder has the rights 777.
We also tried the MySQL 5.6.31 and the bug still appears.

**Comment by html-koder-com** [comment]
@ssddanbrown Hi there? Dou you have any update for me? Thank you.

**Comment by ssddanbrown** [comment]
Thank you for opening this issue. As part of an issue clean-up we're closing off older support issues that may be outdated or irrelevant so therefore I am closing this issue.

If the issue remains and it is one you are still seeking to actively solve please ensure it is still not apparent on the latest version of BookStack then open up a new issue referencing this one.

Sorry if we were not able to solve your original request.
