### ISSUE TITLE
URL returned after login may be wrong (rev. proxy and alias used)

### ISSUE THREAD

**Issue by MatthieuParis** [BookStackApp/BookStack#1377]
**Describe the bug**
When both using a reverse proxy and hosting BookStack in a subdirectory, the URL that is computed after login may be wrong (and then lead to a non existent page).

The path used after login comes from session()->pull('url.intended', '/'); (in app/Http/Controllers/Auth/LoginController.php). This function returns the URL in the hosting server form, with is usually hidden and not explicitly set in the .env file.

Then the URL to redirect the user to is composed by this absolute path value and the base URL, in the function baseUrl (in app/helper.php). As it is not possible to guess the relative part in the path variable because the hidden base URL is not known, there are cases where this leads to errors.

**Steps To Reproduce**
1. Host BookStack in a subdirectory (for example 'test/'), on a special port, for example 10001;
2. Put in front of that server a reverse proxy that uses the beginning of the path (for example 'wiki/') to redirect to the BookStack hosting server;
3. Log in Bookstack and it will try to redirect to the page /wiki/test/test
4. This page does not exist.

**Expected behavior**
I understand that it is usefull to redirect, after login, to the initially requested page. But the method session()->pull('url.intended', '/') reflects the context of the hosting server, which can be quite different from the APP_URL that is declared in the .env file.

I don't know the Laravel framework but it may be possible to extract from the session() object the relative part of the path instead of the absolute path. With just the relative part, the helper function baseUrl should give the expected result.

**Screenshots**
-

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.25.5
 - PHP Version: PHP 7.0.33-0+deb9u3
 - Hosting Method (Nginx/Apache/Docker): Nginx (rev. proxy) + Nginx (hosting) with configuration files included below.

[nginx-hosting.conf.txt](https://github.com/BookStackApp/BookStack/files/3056490/nginx-hosting.conf.txt)
[nginx-rev-proxy.conf.txt](https://github.com/BookStackApp/BookStack/files/3056491/nginx-rev-proxy.conf.txt)

**Additional context**
I would be glad to help in testing a patch. Thanks for your great work.

**Comment by ssddanbrown** [comment]
Hi @MatthieuParis,

I've just deployed a new update, v0.26.2, that fixes some issues found in the URL redirect logic. It's worth updating to that and seeing if this remains an issue.

Let me know either way.

**Comment by MatthieuParis** [comment]
Hi @ssddanbrown,

Firstly, thank you again for your great job. I'm enjoying version 0.26 very much.

I just installed a new instance with v.0.26.2 and tried the proxy nginx configuration again. I still encounter the same problem : everything works fine except the redirection to the root of the wiki after the login.

The first nginx server is used to listen on HTTPS and to redirect every "wiki/something" URL to a secundary nginx server, listening on http://localhost:10001, with just the "something" part of the URL. Upon login into bookstack, my browser is redirected to https://fqdn/wiki/something/something which does not exist.

I would like to use such a configuration to host several services on the same host (bookstack, nextcloud...), and several instances of each service identified by their alias (wiki/mine, wiki/theirs, wiki/other, cloud/one, cloud/two...).

I'll try to look into the PHP code but that means reading a few pages of the Laravel framework documentation at first. I'll keep this page updated.

**Comment by MatthieuParis** [comment]
Hi @ssddanbrown!

I may have found a way to get the correct URL.

When a user is not authenticated, he gets redirected to the login form with the redirect()->guest(...) function. This core Laravel function stores the URL the user was requesting in the session as an absolute URL. But this absolute URL may be quite different from the application URL when BookStack is hosted behind a proxy. In such a case, the function baseUrl(...) may return a wrong URL as it doesn't know the absolute part of the URL used by the service hosting BookStack.

Instead of using the core redirect()->guest(...) function, it is possible to force the intended URL to be recorded in the session as a relative URL and to use the redirect()->to(...) function instead of redirect()->guest(...). With a relative URL, the baseUrl(...) function returns the right URL, based on the application URL declared in the .env file.

The code implied is located in the file app/Http/Middleware/Authenticate.php, in the function handle($request, Closure $next). Here is the code that could be used:
```
        if (!hasAppAccess()) {
            if ($request->ajax()) {
                return response('Unauthorized.', 401);
            } else {
                //return redirect()->guest(baseUrl('/login'));
                session()->put('url.intended', url()->getRequest()->path());
                return redirect()->to(baseUrl('/login'));
            }
        }
```

Hope this helps other BookStack users and doesn't generate other problems.

**Comment by MatthieuParis** [comment]
Hi!

The above code doesn't handle URL parameters such as a searched string. The version below should be better:
```
        if (!hasAppAccess()) {
            if ($request->ajax()) {
                return response('Unauthorized.', 401);
            } else {
		//return redirect()->guest(baseUrl('/login'));
                $uri = url()->getRequest()->getRequestUri();
                $path =	url()->getRequest()->path();
                if (preg_match("|$path\?(.*)$|", "$uri", $match)) {
                     session()->put('url.intended', $path.'?'.$match[1]);
                } else {
                     session()->put('url.intended', $path);
                }
                return redirect()->to(baseUrl('/login'));
            }
        }
```

@ssddanbrown, would you consider this to be worth a pull request?

**Comment by MatthieuParis** [comment]
Hi!

Just tested this behaviour with the 0.27.4 release and I can still reproduce the problem.

The code has changed a little so here are the new lines I use to patch the code of my instances of BookStack :
```
        if (!hasAppAccess()) {
            if ($request->ajax()) {
                return response('Unauthorized.', 401);
            } else {
                // Store the correct URL in the url.intended session parameter
                $uri = url()->getRequest()->getRequestUri();
                $path = url()->getRequest()->path();
                if (preg_match("|$path\?(.*)$|", "$uri", $match)) {
                     session()->put('url.intended', $path.'?'.$match[1]);
                } else {
                     session()->put('url.intended', $path);
                }
                // Redirect with to() and not with guest()
                //return redirect()->guest(url('/login'));
                return redirect()->to(url('/login'));
            }
        }
```

Hope this helps.

Again, @ssddanbrown, please tell me if this is not the right way to send you code. Thanks you for your work: I enjoy every new release a lot.

**Comment by ssddanbrown** [comment]
Thanks for the update on this @MatthieuParis.

To be honest, I can't quite work out why this is not working for you. The redirect works okay for me on my development machine when reverse proxying from nginx to PHP's built-in server, on a sub-path. 

For v0.27 BookStack now uses it's own `Request` class, extending the default one, to essentially fake the source of a request, forcing the `APP_URL` value to be used. The `url.intended` value is generated from the request. 

Would you be able to share you nginx reverse proxy config at all?

**Comment by MatthieuParis** [comment]
Hi @ssddanbrown !

This just happens when the user tries to access a BookStack URL while not identified. The user is then redirected temporarily to the login page and afterwards to a wrong URL, with the subpath appearing twice.

In the 0.26.x version of BookStack, the `url.intended` value was set without taking the `APP_URL` into account before the redirection to the login page. That's why I changed the code.

I did not look into the code of the 0.27.x version, but I reproduce the bug if I do not patch it.

Here is the configuration of the first nginx reverse proxy:
```
server {
  listen                 443 ssl default_server;
  server_name            www.example.net;
  root                   /var/www/html;
                         
  access_log             /var/log/nginx/https_access.log;
  error_log              /var/log/nginx/https_error.log;
                         
  index                  index.php index.html;
  client_max_body_size   1024M;
 
  location /wiki/ {
    proxy_pass http://127.0.0.1:10001/wiki/;
    proxy_redirect http://127.0.0.1:10001/wiki/ https://www.example.net/wiki/;
    proxy_redirect http://localhost:10001/wiki/ https://www.example.net/wiki/;
    proxy_redirect http://www.example.net:10001/wiki/ https://www.example.net/wiki/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
  }
}
```

And the configuration of the second reverse proxy (the one serving BookStack):
```
server {
  listen                 10001 default_server;
  server_name            localhost;
  root                   /var/www/html;
                         
  access_log             /var/log/nginx/bookstack_access.log;
  error_log              /var/log/nginx/bookstack_error.log;
                         
  index                  index.php index.html;
  client_max_body_size   1024M;
 
  location /wiki/one {
    alias                  /var/www/bookstack/instances/one/public;
    try_files              $uri $uri/ @wiki_one;
    access_log             /var/log/nginx/bookstack_one_access.log;
    error_log              /var/log/nginx/bookstack_one_error.log;

    location ~ \.php$ {
      include            snippets/fastcgi-php.conf;
      fastcgi_pass       unix:/var/run/php/php7.3-fpm.sock;
      fastcgi_param      SCRIPT_FILENAME $request_filename;
    }

    location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README) {
      deny all;
    }

    location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
      expires 30d;
      try_files $uri $uri/ @wiki_one;
    }
  }
  
  location @wiki_one {
    rewrite /wiki/one/(.*)$ /wiki/one/index.php?/$1 last;
  }

  location /wiki/two {
    alias                  /var/www/bookstack/instances/two/public;
    try_files              $uri $uri/ @wiki_two;
    access_log             /var/log/nginx/bookstack_two_access.log;
    error_log              /var/log/nginx/bookstack_two_error.log;

    location ~ \.php$ {
      include            snippets/fastcgi-php.conf;
      fastcgi_pass       unix:/var/run/php/php7.3-fpm.sock;
      fastcgi_param      SCRIPT_FILENAME $request_filename;
    }

    location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README) {
      deny all;
    }

    location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
      expires 30d;
      #access_log off;
      try_files $uri $uri/ @wiki_two;
    }
  }
  
  location @wiki_two {
    rewrite /wiki/two/(.*)$ /wiki/two/index.php?/$1 last;
  }

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    include            snippets/fastcgi-php.conf;
    fastcgi_pass       unix:/var/run/php/php7.3-fpm.sock;
    fastcgi_param      SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }
}
```

And finally, here is an extract of the `.env` configuration file for the "one" wiki:
```
APP_URL=https://www.example.net/wiki/one
SESSION_COOKIE_NAME=bookstack_session_one
```

And for the "two" wiki:
```
APP_URL=https://www.example.net/wiki/two
SESSION_COOKIE_NAME=bookstack_session_two
```

Just to be really clear about all that: BookStark works like a charm and this is certainly not a severe bug. I would be pleased to help for a BookStack version with relative URL all over, as suggested in #1342 

Thanks again.

**Comment by AlphaJack** [comment]
> I would be pleased to help for a BookStack version with relative URL all over  

Does it work if you set
```
APP_URL=.
```
in your `.env` file?

**Comment by MatthieuParis** [comment]
Hi AlphaJack!

Thanks for your help on this bug. I’ve been quite busy the past week and I answer a bit late. Sorry for that.

I’ve just installed a new BookStack instance and set APP_URL=.

Firstly, this does not change the fact that a wrong URL is set after login (the subdirectory part appears twice, such as https://www.example.net/wiki/test/wiki/test <https://www.example.net/wiki/test/wiki/test>).

Furthermore, with this setting, the CSS files are not always fetched by the browser. For example, it is OK on the homepage but not after a shelf or a book creation.

As a matter of fact, when I look at the source code, I can see that the dot is used in the URLs. I’m not sure ‘./toto’ is strictly the same as ’toto’ for every browser. And the base URL is wrong as it does not contain the subdirectory part (<meta name="base-url" content=".">).

Feel free to ask me to test other settings. Thank you again.

Matthieu

**Comment by AlphaJack** [comment]
Unfortunately I discovered that it wasn't working in some locations only after I had asked you to try, as you can see from the edit of my comment [here](https://github.com/BookStackApp/BookStack/issues/1342#issuecomment-533753560)

**Comment by philjak** [comment]
I'm facing the same problem. Bookstack is running here:

http://localhost/BookStack/public

After posting to http://localhost/BookStack/public/login 
I get redirected to
http://localhost/BookStack/public/BookStack/public

APP_URL is set to http://localhost/BookStack/public

![image](https://user-images.githubusercontent.com/5772650/67546582-0dc9d280-f6fd-11e9-8218-1a0c6d92f886.png)

**Comment by MatthieuParis** [comment]
Hi @philjak and @ssddanbrown! 

I finally take time to test the 0.28 version of BookStack (version 0.28.3 to be exact). I'm afraid the URL returned after login is still wrong.

The patch I posted upwards is still needed for me:

```
--- Authenticate.php.backup	2020-03-28 13:32:58.972000000 +0100
+++ Authenticate.php	2020-03-28 13:33:45.344000000 +0100
@@ -22,7 +22,17 @@
             if ($request->ajax()) {
                 return response('Unauthorized.', 401);
             } else {
-                return redirect()->guest(url('/login'));
+                // Store the correct URL in the url.intended session parameter
+                $uri = url()->getRequest()->getRequestUri();
+                $path = url()->getRequest()->path();
+                if (preg_match("|$path\?(.*)$|", "$uri", $match)) {
+                     session()->put('url.intended', $path.'?'.$match[1]);
+                } else {
+                     session()->put('url.intended', $path);
+                }
+                // Redirect with to() and not with guest()
+                //return redirect()->guest(url('/login'));
+                return redirect()->to(url('/login'));	    
             }
         }

``` 

Hope that helps!

**Comment by ssddanbrown** [comment]
Hi @MatthieuParis,
Thank you very much for confirming the status and enduring this issue.

Thanks also for offering a pull request. Unfortunately I'm not going to merge it since I'd prefer to fix this at a lower-level, to handle other cases where the system URL is generated from the request.

I would be very grateful if you could try patch described in my comment here, with all other fixes reverted:
https://github.com/BookStackApp/BookStack/issues/2058#issuecomment-619601995

**Comment by MatthieuParis** [comment]
Hi @ssddanbrown,

I just tried the patch you wrote in #2058 with version 0.29.1 and it successfully corrects the bug that is mentioned here :
- after the login page, the root of the wiki is displayed;
- even if one asks for a shelf, book or page URL while being disconnected, the corresponding page is displayed after a successful login.

Thank you very much for both the support you offer to BookStack users and the new features you add to it (permissions, API, usability...). That's really great!

**Comment by MatthieuParis** [comment]
Just tested the #2058 patch with version 0.29.3: it's still successful. Nice!

**Comment by MatthieuParis** [comment]
Patch #2058 is still needed in 0.31.3 and works as expected.

Let's try new API pages actions! Thanks @ssddanbrown

**Comment by ssddanbrown** [comment]
Thanks for confirming @MatthieuParis.

I've assigned this and #2058 to the next feature release milestone so that I remember to work in the changes to core.

**Comment by ssddanbrown** [comment]
Hi @MatthieuParis, Coming back to this, While looking to include the changes into the next release, I'm worried about including any added complexity as it's not a scenario that'll be easy to test nor maintain.

Reading back through the above, The provided example setups look very complicated in terms of URL handling. There's inferred URL re-writing at both the proxy level and direct hosting side, with manual aliases and rewrites included aswell. 

From my testing, Running the BookStack webserver on the root path, then proxying to that instance, works quite well with only a single rewrite needing to be considered (At the proxy level). Could the above setup be simplified greatly by hosting the two instances at the root level, on two different ports, then proxy at the top-level to those two ports based on path? Would mean a lot less URL modification for the request on the way down.

**Comment by MatthieuParis** [comment]
Hi @ssddanbrown!

You're totally right. I've just tested several URL - with 1, 2 or 3 subdirectories after the hostname - that are rewritten on the first proxy to BookStack instances running on the root path, each one on a specific port. The configuration of Nginx (and especially PHP) is simpler. Of course, no patch on the code is needed anymore.

I guess this bug should be closed.

If somebody else wants to deploy several BookStack instances on the same host, here are the Nginx configuration files I use, thanks to Dan's advice.

BookStack hosting:
```
server {
  listen                  10103;
  server_name             localhost;
  root                    /var/www/bookstack/instances/wiki_astuces_20210329/public;
  		          
  access_log              /var/log/nginx/bookstack_access_wiki_astuces_20210329.log;
  error_log               /var/log/nginx/bookstack_error_wiki_astuces_20210329.log;
		          
  index                   index.php index.html;
  client_max_body_size    1024M;
 
  location / {
    try_files             $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    include               snippets/fastcgi-php.conf;
    fastcgi_pass          unix:/var/run/php/php7.3-fpm.sock;
    fastcgi_param         SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }

  location ~ /(?:\.htaccess|data|config|db_structure\.xml|README) {
    deny                  all;
  }

  location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
    expires               30d;
    try_files             $uri $uri/ /index.php?$query_string;
  }
}

server {
  listen                  10102;
  server_name             localhost;
  root                    /var/www/bookstack/instances/wiki_test_20210329/public;
  		          
  access_log              /var/log/nginx/bookstack_access_wiki_test_20210329.log;
  error_log               /var/log/nginx/bookstack_error_wiki_test_20210329.log;
		          
  index                   index.php index.html;
  client_max_body_size    1024M;
 
  location / {
    try_files             $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    include               snippets/fastcgi-php.conf;
    fastcgi_pass          unix:/var/run/php/php7.3-fpm.sock;
    fastcgi_param         SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }

  location ~ /(?:\.htaccess|data|config|db_structure\.xml|README) {
    deny                  all;
  }

  location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
    expires               30d;
    try_files             $uri $uri/ /index.php?$query_string;
  }
}

server {
  listen                  10104;
  server_name             localhost;
  root                    /var/www/bookstack/instances/wiki_doc_20210329/public;
  		          
  access_log              /var/log/nginx/bookstack_access_wiki_doc_20210329.log;
  error_log               /var/log/nginx/bookstack_error_wiki_doc_20210329.log;
		          
  index                   index.php index.html;
  client_max_body_size    1024M;
 
  location / {
    try_files             $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    include               snippets/fastcgi-php.conf;
    fastcgi_pass          unix:/var/run/php/php7.3-fpm.sock;
    fastcgi_param         SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }

  location ~ /(?:\.htaccess|data|config|db_structure\.xml|README) {
    deny                  all;
  }

  location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
    expires               30d;
    try_files             $uri $uri/ /index.php?$query_string;
  }
}
```

Reverse proxy conf:
```
server {
  listen                       443;
  ssl                          on;
  server_name                  exposed.hostname.net;
  root                         /var/www/html;
  			       
  ssl_certificate              /etc/nginx/hostname.crt;
  ssl_certificate_key          /etc/nginx/hostname.key;
  ssl_ciphers                  EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
  ssl_protocols                TLSv1.2;
  ssl_prefer_server_ciphers    on;
  keepalive_timeout            10;
  ssl_session_timeout          5m;

  access_log                   /var/log/nginx/https_access.log;
  error_log                    /var/log/nginx/https_error.log;
		               
  index                        index.php index.html;
  client_max_body_size         1024M;

  location /astuces/ {
    proxy_pass http://127.0.0.1:10103/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
  }

  location /wiki/test/ {
    proxy_pass http://127.0.0.1:10102/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
  }

  location /wiki/sample/doc/ {
    proxy_pass http://127.0.0.1:10104/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
  }
}
```

Thank you a lot, Dan.

**Comment by ssddanbrown** [comment]
Thanks for giving that a try @MatthieuParis  and thanks for sharing the setup for others. Should hopefully result in a more stable setup overall, at least in terms of URL handling.

Will therefore close this off.
